export const APPWRITE_ENDPOINT = import.meta.env.VITE_APPWRITE_ENDPOINT
export const APPWRITE_PROJECT = import.meta.env.VITE_APPWRITE_PROJECT
export const APPWRITE_DATABASE_ID = import.meta.env.VITE_APPWRITE_DATABASE_ID
export const APPWRITE_COURSE_ID = import.meta.env.VITE_APPWRITE_COLLECTION_ID_COURSE
export const APPWRITE_LESSON_ID = import.meta.env.VITE_APPWRITE_COLLECTION_ID_LESSON
export const APPWRITE_QUESTION_ID = import.meta.env.VITE_APPWRITE_COLLECTION_ID_QUESTION
export const APPWRITE_USER_ID = import.meta.env.VITE_APPWRITE_COLLECTION_ID_USER
export const APPWRITE_IMAGE_BUCKET_ID = import.meta.env.VITE_APPWRITE_BUCKET_ID_IMAGE
